export type AgentErrorCode =
  | 'invalid_options'
  | 'seq_gap'
  | 'writer_mismatch'
  | 'not_found'
  | 'already_exists'
  | 'unsupported_feature'
  | 'auth'
  | 'rate_limit'
  | 'server'
  | 'network'
  | 'invalid_response'
  | 'aborted'
  | 'hook_error'
  | 'capability_error'
  | 'writer_busy'
  | 'internal'
  | 'uncertain_invocation'
  | 'interrupted'
  | 'superseded'
  /** A command that needs a live turn reached a handle whose run is no longer running (decision 101). */
  | 'not_running';
